<template>
    <v-container>
        <v-row>
            <v-col>
                <v-text-field
                    label="Regular"
                ></v-text-field>
            </v-col>
        </v-row>
    </v-container>
</template>