version: '3.8'

services:
  web:
    container_name: web_vue_fire
    build: ./docker/web
    ports:
      - "8080:8080"
      - "8081:8081"
    privileged: true
    volumes:
      - ./app:/app:cached
    tty: true
    stdin_open: true
    command: /bin/sh